<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught TypeError: Catalog::orderedSearchAll(): Argument #1 ($id) must be of type int, string given, called in C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\controllers\CatalogController.php on line 189 and defined in C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\models\Catalog.php on line <i>98</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> TypeError: Catalog::orderedSearchAll(): Argument #1 ($id) must be of type int, string given, called in C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\controllers\CatalogController.php on line 189 in C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\models\Catalog.php on line <i>98</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>457680</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\Public\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>545744</td><td bgcolor='#eeeeec'>CatalogController::orderedSearch(  )</td><td title='C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\Public\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>100</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>577144</td><td bgcolor='#eeeeec'>Catalog::orderedSearchAll( <span>$id = </span><span>&#39;PARTNERTEST&#39;</span>, <span>$mode = </span><span>11</span>, <span>$reverse = </span><span>FALSE</span> )</td><td title='C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\controllers\CatalogController.php' bgcolor='#eeeeec'>...\CatalogController.php<b>:</b>189</td></tr>
</table></font>