<br />
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught TypeError: Order::getAmount(): Argument #1 ($pId) must be of type int, string given, called in C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\controllers\OrderController.php on line 62 and defined in C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\models\Order.php on line <i>64</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> TypeError: Order::getAmount(): Argument #1 ($pId) must be of type int, string given, called in C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\controllers\OrderController.php on line 62 in C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\models\Order.php on line <i>64</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>464720</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\Public\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>540144</td><td bgcolor='#eeeeec'>OrderController::setNewCartAmount(  )</td><td title='C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\Public\index.php' bgcolor='#eeeeec'>...\index.php<b>:</b>164</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>592320</td><td bgcolor='#eeeeec'>Order::getAmount( <span>$pId = </span><span>&#39;ID: 1&#39;</span>, <span>$oId = </span><span>1</span> )</td><td title='C:\Users\SMG4\Documents\ESGI\ESGI 2i1\Semestre 2\Projet annuel\projetAnnuel2022\websiteAndApi\api\controllers\OrderController.php' bgcolor='#eeeeec'>...\OrderController.php<b>:</b>62</td></tr>
</table></font>