#ifndef SERVERDATATRANSFER_MACROS_H
#define SERVERDATATRANSFER_MACROS_H

#define READ_OK 1
#define READ_FAILURE -1
#define READ_OVERSIZE -2
#define DATABASE_FAILURE -3

#define SEND_MODE 1
#define RECEIVE_MODE 2

#endif //SERVERDATATRANSFER_MACROS_H